
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on: []

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=horarios_db
      - DB_USERNAME=horarios_user
      - DB_PASSWORD=horarios_password

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=horarios_db
      - MYSQL_USER=horarios_user
      - MYSQL_PASSWORD=horarios_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"

volumes:
  db_data:
